### ISSUE TITLE
Adding title to the images 

### ISSUE THREAD

**Issue by abcnishant007** [lebedov/imshowpair#1]
Hi @lebedov,
first of all, excellent work with this! I missed this matlab's very handy function for a long time. 

I am facing trouble if I pass a title to my plt.title after using imshow, it gets skewed and is shown only on the right image. Am I missing something trivial here?

**Comment by lebedov** [comment]
That behavior is expected: since `imshowpair` creates two subplot axes left to right, a call to `plt.title` will update the last created axis. If you want to create a centered title for the entire figure, you can use `plt.suptitle`.
